apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
    - secrets
    providers:
    - aescbc:
        keys:
        - name: key1
          secret: aW52YWxpZC1leGFtcGxlLWtleS1wbGVhc2UtY2hhbmdl
    - identity: {}
